# Generated by Django 6.0.2 on 2026-02-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="YouTube video ID'sini girin (Örn: jNQXAC9IVRw)", max_length=20, null=True),
        ),
    ]
