# Generated by Django 6.0.2 on 2026-02-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Arama sonuçlarında görünecek 160 karakterlik özet', max_length=160),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Google başlığı (Boş bırakılırsa yazı başlığı kullanılır)', max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video linkini buraya yapıştırın (Örn: https://www.youtube.com/watch?v=jNQXAC9IVRw)', max_length=255, null=True),
        ),
    ]
