# Generated by Django 6.0.2 on 2026-02-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_seo_description_post_seo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Boş bırakırsanız içerikten otomatik özet oluşturulur.', max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Google başlığı (Boş bırakırsanız yazı başlığı otomatik olarak kopyalanır.)', max_length=70),
        ),
    ]
