"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url # Dosyanın en başında olsun
from pathlib import Path
import cloudinary

import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-kzwpveas!iwmulon=p(rv2r)7bq6!0#+#qgf_ex73!b&lgbc@^')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True yerine bunu yaz:
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
# Sadece HTTPS üzerinden cookie gönderimi
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Tarayıcıların siteni iframe içinde göstermesini engeller (Clickjacking koruması)
X_FRAME_OPTIONS = 'DENY'

# XSS saldırılarına karşı ek tarayıcı filtresi
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',    
    'blog',
    'ckeditor',
    'ckeditor_uploader', # Resim yükleme desteği istiyorsan ekle
    'django.contrib.sitemaps',
    'django.contrib.sites', # Bu da gereklidir
    'whitenoise.runserver_nostatic',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
]
SITE_ID = 1 # Genellikle varsayılan budur

CKEDITOR_UPLOAD_PATH = "uploads/"  # Resimlerin kaydedileceği klasör# CKEditor Ayarları (İsteğe bağlı - Araç çubuğunu özelleştirir)
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Sizin eklediğiniz satır:
                'blog.context_processors.category_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse('postgresql://neondb_owner:npg_AYeV6NC0ZoyI@ep-summer-scene-agyevsms-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require')
}

# Neon için gerekli ek ayar
DATABASES['default']['CONN_MAX_AGE'] = 600

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/




# Resimlerin fiziksel olarak kaydedileceği yer
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Cloudinary Ayarları
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dwny1gsw7', # Cloudinary dashboard'daki "Cloud Name"
    'API_KEY': '935849892947271',          # Cloudinary dashboard'daki "API Key"
    'API_SECRET': 'GTXJYedNxsVl5X6WdOw_KLFspT8'    # Cloudinary dashboard'daki "API Secret"
}

# Medya dosyaları için varsayılan depolama alanı
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

cloudinary.config( 
  cloud_name = CLOUDINARY_STORAGE['CLOUD_NAME'], 
  api_key = CLOUDINARY_STORAGE['API_KEY'], 
  api_secret = CLOUDINARY_STORAGE['API_SECRET'],
  secure = True
)



 # settings.py
# settings.py

# 1. Django'nun "bu ayar nerede?" demesini engellemek için (Eski sistemle uyumluluk)
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# 2. Django 4.2+ için YENİ ve GÜVENLİ yapı:
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # WhiteNoise kullanıyorsan en stabil olan budur:
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# 3. Temel Statik Yollar
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 4. WhiteNoise Hata Toleransı (CKEditor hatalarını engeller)
WHITENOISE_MANIFEST_STRICT = False